// Common cities and locations for autocomplete
export const locations = [
  // United States
  'New York, NY, USA',
  'Los Angeles, CA, USA',
  'Chicago, IL, USA',
  'Houston, TX, USA',
  'Phoenix, AZ, USA',
  'Philadelphia, PA, USA',
  'San Antonio, TX, USA',
  'San Diego, CA, USA',
  'Dallas, TX, USA',
  'San Jose, CA, USA',
  'Austin, TX, USA',
  'Jacksonville, FL, USA',
  'Fort Worth, TX, USA',
  'Columbus, OH, USA',
  'Charlotte, NC, USA',
  'San Francisco, CA, USA',
  'Indianapolis, IN, USA',
  'Seattle, WA, USA',
  'Denver, CO, USA',
  'Washington, DC, USA',
  'Boston, MA, USA',
  'El Paso, TX, USA',
  'Nashville, TN, USA',
  'Detroit, MI, USA',
  'Oklahoma City, OK, USA',
  'Portland, OR, USA',
  'Las Vegas, NV, USA',
  'Memphis, TN, USA',
  'Louisville, KY, USA',
  'Baltimore, MD, USA',
  'Milwaukee, WI, USA',
  'Albuquerque, NM, USA',
  'Tucson, AZ, USA',
  'Fresno, CA, USA',
  'Sacramento, CA, USA',
  'Kansas City, MO, USA',
  'Mesa, AZ, USA',
  'Atlanta, GA, USA',
  'Omaha, NE, USA',
  'Colorado Springs, CO, USA',
  'Raleigh, NC, USA',
  'Virginia Beach, VA, USA',
  'Miami, FL, USA',
  'Oakland, CA, USA',
  'Minneapolis, MN, USA',
  'Tulsa, OK, USA',
  'Cleveland, OH, USA',
  'Wichita, KS, USA',
  'Arlington, TX, USA',
  
  // India
  'Mumbai, Maharashtra, India',
  'Delhi, Delhi, India',
  'Bangalore, Karnataka, India',
  'Hyderabad, Telangana, India',
  'Ahmedabad, Gujarat, India',
  'Chennai, Tamil Nadu, India',
  'Kolkata, West Bengal, India',
  'Surat, Gujarat, India',
  'Pune, Maharashtra, India',
  'Jaipur, Rajasthan, India',
  'Lucknow, Uttar Pradesh, India',
  'Kanpur, Uttar Pradesh, India',
  'Nagpur, Maharashtra, India',
  'Indore, Madhya Pradesh, India',
  'Thane, Maharashtra, India',
  'Bhopal, Madhya Pradesh, India',
  'Visakhapatnam, Andhra Pradesh, India',
  'Patna, Bihar, India',
  'Vadodara, Gujarat, India',
  'Ghaziabad, Uttar Pradesh, India',
  'Ludhiana, Punjab, India',
  'Agra, Uttar Pradesh, India',
  'Nashik, Maharashtra, India',
  'Faridabad, Haryana, India',
  'Meerut, Uttar Pradesh, India',
  'Rajkot, Gujarat, India',
  'Varanasi, Uttar Pradesh, India',
  'Srinagar, Jammu and Kashmir, India',
  'Amritsar, Punjab, India',
  'Chandigarh, Chandigarh, India',
  
  // United Kingdom
  'London, England, UK',
  'Manchester, England, UK',
  'Birmingham, England, UK',
  'Glasgow, Scotland, UK',
  'Liverpool, England, UK',
  'Leeds, England, UK',
  'Edinburgh, Scotland, UK',
  'Sheffield, England, UK',
  'Bristol, England, UK',
  'Cardiff, Wales, UK',
  
  // Canada
  'Toronto, Ontario, Canada',
  'Vancouver, British Columbia, Canada',
  'Montreal, Quebec, Canada',
  'Calgary, Alberta, Canada',
  'Ottawa, Ontario, Canada',
  'Edmonton, Alberta, Canada',
  'Winnipeg, Manitoba, Canada',
  'Quebec City, Quebec, Canada',
  'Hamilton, Ontario, Canada',
  'Kitchener, Ontario, Canada',
  
  // Australia
  'Sydney, New South Wales, Australia',
  'Melbourne, Victoria, Australia',
  'Brisbane, Queensland, Australia',
  'Perth, Western Australia, Australia',
  'Adelaide, South Australia, Australia',
  'Gold Coast, Queensland, Australia',
  'Newcastle, New South Wales, Australia',
  'Canberra, ACT, Australia',
  'Sunshine Coast, Queensland, Australia',
  'Wollongong, New South Wales, Australia',
  
  // Germany
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Cologne, Germany',
  'Frankfurt, Germany',
  'Stuttgart, Germany',
  'Düsseldorf, Germany',
  'Dortmund, Germany',
  'Essen, Germany',
  'Leipzig, Germany',
  
  // France
  'Paris, France',
  'Marseille, France',
  'Lyon, France',
  'Toulouse, France',
  'Nice, France',
  'Nantes, France',
  'Strasbourg, France',
  'Montpellier, France',
  'Bordeaux, France',
  'Lille, France',
  
  // Other major cities
  'Tokyo, Japan',
  'Shanghai, China',
  'Beijing, China',
  'Seoul, South Korea',
  'Singapore',
  'Hong Kong',
  'Dubai, UAE',
  'Sydney, Australia',
  'Melbourne, Australia',
  'São Paulo, Brazil',
  'Mexico City, Mexico',
  'Buenos Aires, Argentina',
  'Moscow, Russia',
  'Istanbul, Turkey',
  'Cairo, Egypt',
  'Johannesburg, South Africa',
  'Lagos, Nigeria',
  'Nairobi, Kenya',
  'Bangkok, Thailand',
  'Jakarta, Indonesia',
  'Manila, Philippines',
  'Kuala Lumpur, Malaysia',
  'Ho Chi Minh City, Vietnam',
  'Dhaka, Bangladesh',
  'Karachi, Pakistan',
  'Tehran, Iran',
  'Riyadh, Saudi Arabia',
  'Tel Aviv, Israel',
  'Athens, Greece',
  'Rome, Italy',
  'Madrid, Spain',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Vienna, Austria',
  'Zurich, Switzerland',
  'Stockholm, Sweden',
  'Copenhagen, Denmark',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Dublin, Ireland',
  'Lisbon, Portugal',
  'Warsaw, Poland',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Bucharest, Romania',
  'Sofia, Bulgaria',
  'Zagreb, Croatia',
];

// Filter locations based on search query
export const filterLocations = (query) => {
  if (!query || query.length < 1) return [];
  const lowerQuery = query.toLowerCase();
  return locations
    .filter(location => location.toLowerCase().includes(lowerQuery))
    .slice(0, 10); // Limit to 10 results
};

